# This file was generated by GoReleaser. DO NOT EDIT.
cask "smplify" do
  version "0.32.2"

  on_macos do
    on_intel do
      sha256 "4e4f96ca514f3e1b3b4bd3502f87d411815af9b5a438d33d48b3db0b6c71ba1e"
      url "https://cli.smplify.com/releases/v#{version}/smplify_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "03a6034270f87299d91860eb77c55dd3f7dac67e8a294128aaed23e461646045"
      url "https://cli.smplify.com/releases/v#{version}/smplify_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2001af18303fbf0f7eaff547a8b3b0d7876e322638dd584222397bac84f72bac"
      url "https://cli.smplify.com/releases/v#{version}/smplify_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "04b0e94bc8c02f6b47a3bb7a925654fddb4f3307a2eb2700d7ddd970b0b585e0"
      url "https://cli.smplify.com/releases/v#{version}/smplify_linux_arm64.tar.gz"
    end
  end

  name "smplify"
  desc "Smplify CLI — the official command line for the Smplify Apple-focused MDM platform."
  homepage "https://cli.smplify.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smplify"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/smplify"]
    end
  end

  # No zap stanza required

end
